import type { EvictionInfo, EvictionRecipe, UsedSymbol } from '../types/index';

// ─── Tier 1 recipe definitions ───────────────────────────────────────────────

/**
 * Deep equality with lodash.isEqual semantics: SameValueZero for primitives,
 * value comparison for Date / RegExp / Error / boxed primitives, element-wise
 * arrays and typed arrays, unordered Map and Set, own enumerable string and
 * symbol keys, lodash's constructor check, and cycle handling.
 * Verified against lodash by test/recipes.test.ts.
 */
export const IS_EQUAL_TS = `\
/**
 * Deep equality — native replacement for lodash.isEqual.
 * Generated by DepTax. No runtime dependencies.
 */
export function isEqual(a: unknown, b: unknown): boolean {
  return equal(a, b, new Map());
}

const toTag = (v: unknown): string => {
  const tag = Object.prototype.toString.call(v);
  return tag === '[object Arguments]' ? '[object Object]' : tag;
};

function equal(a: unknown, b: unknown, stack: Map<object, object>): boolean {
  if (a === b) { return true; }
  if (a == null || b == null || (typeof a !== 'object' && typeof b !== 'object')) {
    return a !== a && b !== b; // NaN equals NaN
  }
  const tag = toTag(a);
  if (tag !== toTag(b)) { return false; }
  const x = a as object;
  const y = b as object;

  switch (tag) {
    case '[object Boolean]':
    case '[object Date]':
    case '[object Number]': {
      const p = +(x as number);
      const q = +(y as number);
      return p === q || (p !== p && q !== q);
    }
    case '[object String]':
    case '[object RegExp]':
      return String(x) === String(y);
    case '[object Error]':
      return (x as Error).name === (y as Error).name && (x as Error).message === (y as Error).message;
    case '[object Symbol]':
      return Symbol.prototype.valueOf.call(x) === Symbol.prototype.valueOf.call(y);
    case '[object ArrayBuffer]':
      return bytesEqual(new Uint8Array(x as ArrayBuffer), new Uint8Array(y as ArrayBuffer));
    case '[object DataView]': {
      const p = x as DataView;
      const q = y as DataView;
      return p.byteOffset === q.byteOffset && bytesEqual(
        new Uint8Array(p.buffer, p.byteOffset, p.byteLength),
        new Uint8Array(q.buffer, q.byteOffset, q.byteLength),
      );
    }
  }

  const seenA = stack.get(x);
  const seenB = stack.get(y);
  if (seenA && seenB) { return seenA === y && seenB === x; }
  stack.set(x, y);
  stack.set(y, x);
  try {
    if (Array.isArray(x) || ArrayBuffer.isView(x)) {
      const p = x as ArrayLike<unknown>;
      const q = y as ArrayLike<unknown>;
      if (p.length !== q.length) { return false; }
      for (let i = 0; i < p.length; i++) {
        if (!equal(p[i], q[i], stack)) { return false; }
      }
      return true;
    }
    if (tag === '[object Map]' || tag === '[object Set]') {
      const p = x as Map<unknown, unknown> | Set<unknown>;
      const q = y as Map<unknown, unknown> | Set<unknown>;
      if (p.size !== q.size) { return false; }
      return unorderedEqual([...p], [...q], stack);
    }
    if (tag !== '[object Object]') { return false; }
    return objectsEqual(x, y, stack);
  } finally {
    stack.delete(x);
    stack.delete(y);
  }
}

function ownKeys(o: object): PropertyKey[] {
  const keys: PropertyKey[] = Object.keys(o);
  for (const s of Object.getOwnPropertySymbols(o)) {
    if (Object.prototype.propertyIsEnumerable.call(o, s)) { keys.push(s); }
  }
  return keys;
}

function objectsEqual(x: object, y: object, stack: Map<object, object>): boolean {
  const keys = ownKeys(x);
  if (keys.length !== ownKeys(y).length) { return false; }
  let comparedConstructor = false;
  for (const key of keys) {
    if (!Object.prototype.hasOwnProperty.call(y, key)) { return false; }
    const p = (x as Record<PropertyKey, unknown>)[key];
    const q = (y as Record<PropertyKey, unknown>)[key];
    if (p !== q && !equal(p, q, stack)) { return false; }
    if (key === 'constructor') { comparedConstructor = true; }
  }
  if (!comparedConstructor) {
    const cx = (x as { constructor?: unknown }).constructor;
    const cy = (y as { constructor?: unknown }).constructor;
    const plain = (c: unknown) => typeof c === 'function' && c instanceof (c as new () => unknown);
    if (cx !== cy && 'constructor' in x && 'constructor' in y && !(plain(cx) && plain(cy))) {
      return false;
    }
  }
  return true;
}

function unorderedEqual(p: unknown[], q: unknown[], stack: Map<object, object>): boolean {
  const matched = new Set<number>();
  for (const a of p) {
    let found = false;
    for (let i = 0; i < q.length; i++) {
      if (!matched.has(i) && (a === q[i] || equal(a, q[i], stack))) {
        matched.add(i);
        found = true;
        break;
      }
    }
    if (!found) { return false; }
  }
  return true;
}

function bytesEqual(p: Uint8Array, q: Uint8Array): boolean {
  if (p.length !== q.length) { return false; }
  for (let i = 0; i < p.length; i++) {
    if (p[i] !== q[i]) { return false; }
  }
  return true;
}
`;

/** Native replacement for `uuid.v4()` without arguments. */
const UUID_V4_TS = `\
/**
 * UUID v4 — native replacement for the uuid package's v4().
 * Generated by DepTax. Uses the platform's cryptographic random UUID.
 */
export function v4(): string {
  return globalThis.crypto.randomUUID();
}
`;

/** Native Dart replacement for quiver's `isBlank`. */
const IS_BLANK_DART = `\
/// isBlank — native replacement for quiver/strings.dart isBlank.
/// Generated by DepTax. No package dependencies.
bool isBlank(String? s) => s == null || s.trim().isEmpty;
`;

const IS_EQUAL_OUTPUT = {
  nativeCode: IS_EQUAL_TS,
  nativeImportPath: '../utils/native_helpers/is_equal',
  outputFileName: 'is_equal.ts',
};

const RECIPES: EvictionRecipe[] = [
  {
    packageName: 'lodash',
    symbolName: 'isEqual',
    matches: [['lodash', 'isEqual'], ['lodash/isEqual', 'default'], ['lodash/isEqual.js', 'default']],
    ...IS_EQUAL_OUTPUT,
  },
  {
    packageName: 'lodash-es',
    symbolName: 'isEqual',
    matches: [['lodash-es', 'isEqual'], ['lodash-es/isEqual', 'default'], ['lodash-es/isEqual.js', 'default']],
    ...IS_EQUAL_OUTPUT,
  },
  {
    packageName: 'lodash.isequal',
    symbolName: 'isEqual',
    matches: [['lodash.isequal', 'default']],
    ...IS_EQUAL_OUTPUT,
  },
  {
    packageName: 'uuid',
    symbolName: 'v4',
    matches: [['uuid', 'v4']],
    nativeCode: UUID_V4_TS,
    nativeImportPath: '../utils/native_helpers/uuid_v4',
    outputFileName: 'uuid_v4.ts',
    // uuid's v4(options, buffer, offset) has no native equivalent; only plain calls qualify.
    maxArity: 0,
    requires: 'Node.js 19+, or a browser page served over HTTPS',
  },
  {
    packageName: 'quiver',
    symbolName: 'isBlank',
    matches: [['package:quiver/strings.dart', 'isBlank'], ['package:quiver/quiver.dart', 'isBlank']],
    nativeCode: IS_BLANK_DART,
    nativeImportPath: '../utils/native_helpers/is_blank.dart',
    outputFileName: 'is_blank.dart',
  },
];

// ─── Public API ───────────────────────────────────────────────────────────────

/** Recipe replacing `symbol` of `packageName`, if one exists and its preconditions hold. */
export function recipeFor(packageName: string, symbol: UsedSymbol): EvictionRecipe | undefined {
  const recipe = RECIPES.find((r) =>
    r.packageName === packageName && r.matches.some(([m, n]) => m === symbol.module && n === symbol.name));
  if (!recipe) { return undefined; }
  if (recipe.maxArity !== undefined) {
    const passedAsValue = symbol.references > symbol.callArities.length;
    if (passedAsValue || symbol.callArities.some((a) => a > recipe.maxArity!)) { return undefined; }
  }
  return recipe;
}

/**
 * A package can be evicted by recipe only when every symbol it is used for at
 * runtime has a recipe whose preconditions hold at every call site.
 */
export function lookup(packageName: string, runtimeSymbols: UsedSymbol[], usesWholeModule: boolean): EvictionInfo {
  const covered: string[] = [];
  const uncovered: string[] = [];
  for (const s of runtimeSymbols) {
    const label = s.name === 'default' ? s.module : s.name;
    (recipeFor(packageName, s) ? covered : uncovered).push(label);
  }
  if (usesWholeModule) { uncovered.push('*'); }
  const available = covered.length > 0 && uncovered.length === 0;
  return { available, strategy: available ? 'recipe' : null, covered, uncovered };
}

export function getRecipe(packageName: string, symbolName: string): EvictionRecipe | undefined {
  return RECIPES.find((r) => r.packageName === packageName && r.symbolName === symbolName);
}
