import type { EvictionRecipe, ScoredPackage, UsedSymbol } from '../types/index';

// ─── Tier 1 recipe definitions ───────────────────────────────────────────────

/**
 * Full TypeScript deep-equality helper (spec Section 5.2, Step 2).
 * Drop-in replacement for `lodash.isEqual`.
 */
const IS_EQUAL_TS = `\
/**
 * Deep equality — native replacement for lodash.isEqual.
 * Generated by DepTax. No runtime dependencies.
 */
export function isEqual(a: unknown, b: unknown): boolean {
  if (a === b) { return true; }
  if (a === null || b === null) { return false; }
  if (typeof a !== typeof b) { return false; }
  if (typeof a !== 'object') { return false; }

  if (Array.isArray(a)) {
    if (!Array.isArray(b)) { return false; }
    if (a.length !== b.length) { return false; }
    for (let i = 0; i < a.length; i++) {
      if (!isEqual(a[i], (b as unknown[])[i])) { return false; }
    }
    return true;
  }

  if (Array.isArray(b)) { return false; }

  const objA = a as Record<string, unknown>;
  const objB = b as Record<string, unknown>;
  const keysA = Object.keys(objA);
  const keysB = Object.keys(objB);
  if (keysA.length !== keysB.length) { return false; }
  for (const key of keysA) {
    if (!Object.prototype.hasOwnProperty.call(objB, key)) { return false; }
    if (!isEqual(objA[key], objB[key])) { return false; }
  }
  return true;
}
`;

/** Native replacement for `uuid.v4` — wraps `crypto.randomUUID()`. */
const UUID_V4_TS = `\
/**
 * UUID v4 — native replacement for the uuid package's v4 function.
 * Generated by DepTax. Requires Node ≥ 15 or any modern browser.
 */
export function v4(): string {
  return crypto.randomUUID();
}
`;

/** Native Dart replacement for `quiver.isBlank`. */
const IS_BLANK_DART = `\
/// isBlank — native replacement for quiver/strings.dart isBlank.
/// Generated by DepTax. No package dependencies.
bool isBlank(String? s) => s == null || s.trim().isEmpty;
`;

// ─── Registry map: "packageName/symbolName" → EvictionRecipe ─────────────────

const RECIPES = new Map<string, EvictionRecipe>([
  [
    'lodash/isEqual',
    {
      packageName: 'lodash',
      symbolName: 'isEqual',
      nativeCode: IS_EQUAL_TS,
      nativeImportPath: '../utils/native_helpers/is_equal',
      outputFileName: 'is_equal.ts',
    },
  ],
  [
    'uuid/v4',
    {
      packageName: 'uuid',
      symbolName: 'v4',
      nativeCode: UUID_V4_TS,
      nativeImportPath: '../utils/native_helpers/uuid_v4',
      outputFileName: 'uuid_v4.ts',
    },
  ],
  [
    'quiver/isBlank',
    {
      packageName: 'quiver',
      symbolName: 'isBlank',
      nativeCode: IS_BLANK_DART,
      nativeImportPath: '../utils/native_helpers/is_blank',
      outputFileName: 'is_blank.dart',
    },
  ],
]);

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Look up whether any used symbols in `usedSymbols` have an eviction recipe
 * for the given `packageName`.
 *
 * Returns:
 *   - `evictionAvailable: true` if at least one recipe matches a used symbol.
 *   - `evictionStrategy: 'recipe'` when a recipe is available, otherwise `null`.
 */
export function lookup(
  packageName: string,
  usedSymbols: UsedSymbol[],
): {
  evictionAvailable: boolean;
  evictionStrategy: ScoredPackage['evictionStrategy'];
} {
  for (const sym of usedSymbols) {
    const key = `${packageName}/${sym.symbolName}`;
    if (RECIPES.has(key)) {
      return { evictionAvailable: true, evictionStrategy: 'recipe' };
    }
  }
  return { evictionAvailable: false, evictionStrategy: null };
}

/**
 * Retrieve the full `EvictionRecipe` for a specific package/symbol pair,
 * or `undefined` if no recipe exists.
 */
export function getRecipe(packageName: string, symbolName: string): EvictionRecipe | undefined {
  return RECIPES.get(`${packageName}/${symbolName}`);
}
